name: gifts_prices

on:
  workflow_dispatch:

jobs:
  generate-prices:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: nxrix/workflows
          token: ${{ secrets.PAT0 }}
          path: workflows

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run gifts_prices.js
        run: node workflows/gifts_prices.js
        env:
          API0_URL: ${{ secrets.API0_URL }}
          API0_KEY: ${{ secrets.API0_KEY }}

      - name: Commit price changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gifts/
          git commit -m "^ prices"
          git pull --rebase
          git push


  generate-prices2:
    needs: generate-prices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: nxrix/workflows
          token: ${{ secrets.PAT0 }}
          path: workflows

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run gifts_prices2.js
        run: node workflows/gifts_prices2.js
        env:
          API0_URL: ${{ secrets.API0_URL }}
          API0_KEY: ${{ secrets.API0_KEY }}

      - name: Commit price changes 2
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gifts/t/
          git commit -m "^ prices 2"
          git pull --rebase
          git push

  generate-images:
    needs: generate-prices2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: nxrix/workflows
          token: ${{ secrets.PAT0 }}
          path: workflows

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run gifts_prices_image.js
        run: node workflows/gifts_prices_image.js

      - name: Commit image changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gifts/
          git commit -m "^ images"
          git pull --rebase
          git push

  generate-images2:
    needs: generate-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: nxrix/workflows
          token: ${{ secrets.PAT0 }}
          path: workflows

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run gifts_prices_image2.js
        run: node workflows/gifts_prices_image2.js

      - name: Commit image changes 2
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gifts/t/
          git commit -m "^ images 2"
          git pull --rebase
          git push
